	-- Query 1: Total Users 
	select count(*) as Total_Users
	from users;

	-- Query 2: Total Courses
	select count(*) as Total_Courses
	from courses;

	-- Query 3: Total Revenue
	select round(sum(amount),2) as Total_Revenue
	from payments
	where payment_status='success';

	-- Query 4: Total Enrollments
	select count(*) as Total_Enrollments
	from enrollments;

	-- Query 5: Total Certificates Issued
	select count(*) as Total_Certificates_Issued
	from certificates;

-- Query 6
-- Find the overall course completion rate (%).
Select round(sum(completion_status='completed')*100.0 / count(*),2) as Course_completion_rate
from enrollments;

-- Query 7
-- Find the average course rating (ignore NULL ratings).
Select round(avg(rating_given),2) as Average_course_rating
from enrollments;

-- Query 8
-- Find the total number of AI chats.
select count(*) as Total_No_Of_AI_Chats
from AI_Chats;

-- Query 9
-- Find the average AI satisfaction rating.
select round(avg(satisfaction_rating),2) as Average_AI_satisfaction_rating
from AI_chats;

-- Query 10
-- Find the total number of support tickets.
select count(*) as total_number_of_support_tickets
from support_tickets;

-- 11.Show the total revenue generated by each subscription plan (only successful payments).
select sum(amount) as Total_Revenue, s.plan_name
from payments p
join subscription_Plans s
on p.subscription_id = s.subscription_id
where payment_status='Success'
group by  plan_name;

-- 12.Find the monthly revenue trend.
select sum(amount) as revenue, DATE_FORMAT(payment_date,'%Y-%m') as months
from payments
group by DATE_FORMAT(payment_date,'%Y-%m')
order by DATE_FORMAT(payment_date,'%Y-%m');

-- 13.Show revenue by payment method.
select sum(amount)as Revenue , payment_method
from payments
where payment_status = 'Success'
group by payment_method;

-- 14.Find the average payment amount for each subscription plan.
select round(avg(amount),2) as Average_payment_Amount ,s.plan_name
from payments p
join subscription_plans s 
on p.subscription_id = s.subscription_id
WHERE payment_status='Success'
group by s.plan_name;

-- 15.Calculate the total discount given and the average discount per payment.
select sum(discount_amount) as Total_discount_Given , avg(discount_amount) as average_discount_per_payment
from payments;

-- Query 16
-- Show the top 10 highest-rated courses based on the average rating_given.
select c.course_name,avg(e.rating_given)
from courses c 
join enrollments e
on c.course_id = e.course_id
group by c.course_name
order by avg(e.rating_given) desc limit 10;

-- Query 17
-- Find the top 5 instructors with the highest number of enrollments.
select i.instructor_id,i.first_name, count(e.enrollment_id) as No_of_Enrollments
from instructors i
join courses c
on i.instructor_id = c.instructor_id
join enrollments e 
on c.course_id = e.course_id
group by i.instructor_id,i.first_name
order by count(e.enrollment_id) desc limit 5;

-- Query 18
-- Show the number of enrollments by course category.
select count(e.enrollment_id) as No_of_Enrollments, ct.category_name
from categories ct
join courses c
on ct.category_id = c.category_id
join enrollments e 
on c.course_id = e.course_id
group by ct.category_name;

select * from categories;

-- Query 19
-- Find the average course completion percentage for each difficulty level.
select avg(e.completion_percentage) as Average_Course_completion_Percentage , c.difficulty
from courses c 
join enrollments e
on c.course_id = e.course_id
group by c.difficulty;

-- Query 20
-- List the top 10 most enrolled courses.
select c.course_name, count(enrollment_id) as No_of_Enrolled_users
from courses c 
join enrollments e
on c.course_id = e.course_id
group by c.course_name
order by count(enrollment_id) desc limit 10;

-- Query 21
-- Find the top 5 most active users based on total logins.
select u.user_id ,u.first_name, count(login_id) as Total_logins
from users u 
join login_history l 
on u.user_id = l.user_id
group by  u.user_id ,u.first_name
order by count(login_id) desc limit 5;
 
-- Query 22
-- Find the average session duration by device.
select device,avg(session_duration_minutes) as average_session_duration
from login_history
group by device;
 
-- Query 23
-- Show the top 10 most used platform features.
select feature_name, count(*) as Most_used_features
from feature_usage
group by feature_name
order by count(*) desc limit 10;

-- Query 24
-- Find the average AI satisfaction rating for each topic.
select avg(satisfaction_rating) as average_AI_satisfaction_rating, topic
from AI_chats
group by topic;

-- Query 25
-- Find the support ticket resolution rate (%).
select round(sum(ticket_status='Resolved')*100.0/count(*),2) as support_ticket_resolution_rate 
from support_tickets;

-- 26.Find the names of all users who have spent more than the average payment amount.
select u.user_id, u.first_name, sum(p.amount) as Total_Spending
from users u
join payments p 
on u.user_id = p.user_id
WHERE p.payment_status = 'Success'
group by u.user_id, u.first_name
having sum(p.amount)  > (select avg(amount) from payments);

-- Query 27
-- Find all courses that have more enrollments than the average number of enrollments per course. 
select c.course_name,c.course_id, count(e.enrollment_id) as Total_Enrollment
from courses c
join Enrollments e 
on c.course_id = e.course_id 
group by c.course_id, c.course_name
having count(e.enrollment_id) > (select avg(Total_Enrollment) from (select c.course_name,c.course_id, count(e.enrollment_id) as Total_Enrollment
from courses c
join Enrollments e 
on c.course_id = e.course_id 
group by c.course_id, c.course_name) as x) ;

-- Query 28
-- Find the users who have enrolled in more courses than the average number of enrollments per user.
select u.user_id, u.first_name, count(e.enrollment_id) as Total_Enrollment
from users u 
join enrollments e 
on u.user_id = e.user_id
group by u.user_id, u.first_name
having count(e.enrollment_id) > (select avg(Total_Enrollment) 
from (select u.user_id, u.first_name, count(e.enrollment_id) as Total_Enrollment
from users u 
join enrollments e 
on u.user_id = e.user_id
group by u.user_id, u.first_name) as x);

-- Query 29
-- Rewrite Query 28 using a CTE.
-- Find the users who have enrolled in more courses than the average number of enrollments per user.
with Total_Enrollment as 
(select u.user_id, u.first_name, count(e.enrollment_id) as Total_Enrollments
from users u 
join enrollments e 
on u.user_id = e.user_id
group by u.user_id, u.first_name)
select * from Total_Enrollment 
where Total_Enrollments > ( select avg(Total_Enrollments)  
from Total_Enrollment);

-- Query 30
-- Find the top 5 course categories based on their average course completion percentage.
with course_percentage as 
(select ct.category_id , ct.category_name,avg(e.completion_percentage) as Avg_course_completion_percentage
 from Categories ct
 join courses c 
 on ct.category_id = c.category_id 
 join enrollments e 
 on c.course_id = e.course_id
 GROUP BY ct.category_id, ct.category_name)
 select * from course_percentage
 order by Avg_course_completion_percentage desc limit 5;
 
-- Query 31
 -- Find the top 3 subscription plans by total successful payment revenue, and show their revenue.
with Revenue as (select s.subscription_id,s.plan_name, sum(p.amount) as total_successful_payment_revenue 
from subscription_Plans s
join payments p
on s.subscription_id = p.subscription_id
where payment_status = 'Success'
group by s.subscription_id,s.plan_name)
select * from Revenue 
order by total_successful_payment_revenue desc limit 3;

-- Query 32
-- Find the top 5 courses based on total enrollments, but only include courses whose average completion percentage 
-- is greater than 70%.
with Top_5 as (select c.course_id, c.course_name, count(e.enrollment_id) as Total_Enrollments, 
avg(e.completion_percentage) as average_completion_percentage
from courses c 
join enrollments e 
on c.course_id = e.course_id
group by c.course_id, c.course_name
)
select * from Top_5 
where average_completion_percentage > 70
order by Total_Enrollments desc limit 5;

-- Query 33
-- Rank all courses based on their total number of enrollments, from highest to lowest, using ROW_NUMBER().
select c.course_id, c.course_name, count(e.enrollment_id) as Total_Enrollment, row_number() over (order by count(e.enrollment_id) desc) as course_rank
from courses c 
join enrollments e 
on c.course_id = e.course_id
group by c.course_id, c.course_name;

-- Query 34 — RANK()
-- Rank all courses based on total enrollments using RANK(). 
-- If two courses have the same number of enrollments, they should receive the same rank.
select c.course_id,c.course_name, rank() over (order by count(e.enrollment_id) desc) as Course_Rank
from courses c 
join enrollments e 
on c.course_id = e.course_id
group by c.course_id, c.course_name;

-- Query 35 — DENSE_RANK()
-- Rank all courses based on total enrollments using DENSE_RANK().
-- Courses with the same number of enrollments should receive the same rank, and the next rank should not be skipped.
select c.course_id,c.course_name, dense_rank() over (order by count(e.enrollment_id) desc) as Course_Rank
from courses c 
join enrollments e 
on c.course_id = e.course_id
group by c.course_id, c.course_name;

-- Query 36 — PARTITION BY
-- Rank courses within each difficulty level based on their total enrollments.
select c.course_id, c.course_name,
Rank() over (partition by c.difficulty order by count(e.enrollment_id) desc) as Course_Rank, c.difficulty 
from courses c 
join enrollments e 
on c.course_id = e.course_id
group by c.course_id, c.course_name,c.difficulty ;

-- Query 37 — LAG()
-- For each month, show the monthly revenue and the previous month's revenue.
with Prev_mont_rev as(select sum(amount) as revenue, DATE_FORMAT(payment_date,'%Y-%m') as months
from payments
where payment_status = 'success'
group by DATE_FORMAT(payment_date,'%Y-%m')
)
select *, lag(revenue) over (order by months) as Previous_Month_Revenue from Prev_mont_rev;

-- Query 38 — Month-over-Month Revenue Growth
with Prev_mont_rev as(select sum(amount) as revenue, DATE_FORMAT(payment_date,'%Y-%m') as months
from payments
where payment_status = 'success'
group by DATE_FORMAT(payment_date,'%Y-%m')
),
prev_mont_rev2 as(select *, lag(revenue) over (order by months) as Previous_Month_Revenue
from Prev_mont_rev)
select *, ((revenue-Previous_Month_Revenue)/Previous_Month_Revenue) * 100 as Month_over_Month_Revenue_Growth
from prev_mont_rev2;

-- Query 39 — LEAD()
-- For each month, show the current month's revenue and the next month's revenue.
with Prev_mont_rev as(select sum(amount) as revenue, DATE_FORMAT(payment_date,'%Y-%m') as months
from payments
where payment_status = 'success'
group by DATE_FORMAT(payment_date,'%Y-%m')
)
select *, lag(revenue) over (order by months) as Previous_Month_Revenue from Prev_mont_rev;

-- Query 40 — Combine Window Functions + Business Logic
-- For each course, show its total enrollments and its percentage contribution to all enrollments.
with tot_enr as(select c.course_id,c.course_name, count(e.enrollment_id)  as Course_Enrollment, 
sum(count(e.enrollment_id)) over() as Total_Enrollment
from courses c 
join enrollments e 
on c.course_id = e.course_id
group by c.course_id, c.course_name)
select *, Course_Enrollment / Total_Enrollment * 100
from tot_enr;

-- Question 1 — User Spending
-- Find the top 10 users by total successful payment amount.
select u.user_id, sum(p.amount) as Total_Amount
from users u 
join payments p 
on u.user_id = p.user_id
where payment_status = 'success'
group by user_id
order by sum(p.amount) desc limit 10;

-- Find courses whose average completion percentage is higher than the overall average completion percentage across 
-- all enrollments.
select c.course_id, c.course_name, avg(e.completion_percentage) as Avg_completion
from courses c 
join enrollments e 
on c.course_id = e.course_id 
group by c.course_id, c.course_name 
having avg(e.completion_percentage) > (select avg(completion_percentage) from enrollments);

-- For each course category, calculate:
-- category_name
-- total_enrollments
-- category_rank
-- Rank categories from highest to lowest enrollment.
-- All categories should be ranked together.
WITH Category_rank AS (
    SELECT
        ct.category_id,
        ct.category_name,
        COUNT(e.enrollment_id) AS Total_Enrollment
    FROM Categories ct
    JOIN Courses c
        ON ct.category_id = c.category_id
    JOIN Enrollments e
        ON c.course_id = e.course_id
    GROUP BY ct.category_id, ct.category_name
)
SELECT *,
       RANK() OVER (
           ORDER BY Total_Enrollment DESC
       ) AS Categories_Rank
FROM Category_rank;

-- Q4
-- For every month, show:
-- month
-- revenue
-- previous_month_revenue
-- revenue_growth_percentage
-- Only successful payments count.
with Month_Revenue as (select DATE_FORMAT(payment_date,'%Y-%m') as months, sum(amount) as Revenue
from payments
where payment_status = 'success'
group by DATE_FORMAT(payment_date,'%Y-%m') ),
prev_month_rev as(select * , lag(Revenue) over (order by  months) as previous_month_revenue
from Month_Revenue)
select *, ((revenue-Previous_Month_Revenue)/Previous_Month_Revenue) * 100 as revenue_growth_percentage
from prev_month_rev;


-- Find users who:
-- have logged in more times than the average number of logins per user, AND
-- have completed at least one course.
-- Return:
-- user_id
-- first_name
-- total_logins
-- completed_courses
WITH User_Logins AS (
    SELECT
        u.user_id,
        u.first_name,
        COUNT(l.login_id) AS total_logins
    FROM users u
    JOIN login_history l
        ON u.user_id = l.user_id
    GROUP BY u.user_id, u.first_name
),

Completed_Courses AS (
    SELECT
        user_id,
        COUNT(*) AS completed_courses
    FROM enrollments
    WHERE completion_status = 'Completed'
    GROUP BY user_id
)

SELECT
    ul.user_id,
    ul.first_name,
    ul.total_logins,
    cc.completed_courses
FROM User_Logins ul
JOIN Completed_Courses cc
    ON ul.user_id = cc.user_id
WHERE ul.total_logins > (
    SELECT AVG(total_logins)
    FROM User_Logins
)
AND cc.completed_courses >= 1;

